import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import crypto from 'node:crypto';

const ROOT=path.dirname(fileURLToPath(import.meta.url));
const PORT=Number(process.env.PORT||8787);
const rooms=new Map();
const clients=new Map();
const now=()=>Date.now();
const code=()=>String(Math.floor(100000+Math.random()*900000));
const id=()=>crypto.randomBytes(9).toString('base64url');
const FIELD_PATTERNS=["STRAIGHT_LINE","LEFT_CURVE","RIGHT_CURVE","HIGH_ARC","LOW_ROUTE","S_CURVE","GATE_CHAIN","BANK_STARS"];
const makeField=()=>({pattern:FIELD_PATTERNS[crypto.randomInt(0,FIELD_PATTERNS.length)],seed:crypto.randomInt(1,2147483647),catchPos:{x:0.15+Math.random()*0.70,y:0.20+Math.random()*0.60}});
const nextPlayable=(r,from)=>{for(let i=1;i<=r.players.length;i++){const n=(from+i)%r.players.length;if(r.players[n].alive!==false&&r.players[n].connected!==false)return n}return from};
function pub(r){return {code:r.code,status:r.status,hostId:r.hostId,currentIndex:r.currentIndex,seq:r.seq,field:r.field||null,visibility:r.visibility||'private',stageId:r.stageId||null,difficulty:r.difficulty||'NORMAL',players:r.players.map(p=>({id:p.id,name:p.name,characterId:p.characterId,ready:p.ready,connected:p.connected,slot:p.slot,alive:p.alive!==false}))};}
function send(room,type,data={}){room.seq++;const msg=`event: message\ndata: ${JSON.stringify({type,seq:room.seq,room:pub(room),...data})}\n\n`;for(const p of room.players){const set=clients.get(p.id);if(set)for(const res of set){try{res.write(msg)}catch{}}}}
function json(res,status,obj){res.writeHead(status,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify(obj));}
async function body(req){let s='';for await(const c of req){s+=c;if(s.length>1e6)throw Error('too large')}return s?JSON.parse(s):{};}
function roomOf(c){return rooms.get(String(c||''));}
function player(r,t){return r?.players.find(p=>p.token===t);}
function cleanup(){for(const [c,r] of rooms)if(now()-r.touched>2*60*60*1000){rooms.delete(c);}}
setInterval(cleanup,60000).unref();
const server=http.createServer(async(req,res)=>{try{
 const u=new URL(req.url,'http://x');
 if(u.pathname==='/health')return json(res,200,{ok:true,rooms:rooms.size});
 if(u.pathname==='/api/rooms'&&req.method==='GET'){const list=[...rooms.values()].filter(r=>r.status==='LOBBY'&&r.visibility==='public'&&r.players.length<4).map(r=>({code:r.code,stageId:r.stageId,difficulty:r.difficulty,hostName:r.players[0]?.name||'HOST',players:r.players.length,maxPlayers:4,createdAt:r.createdAt||r.touched}));return json(res,200,{rooms:list});}
 if(u.pathname==='/api/room/create'&&req.method==='POST'){const b=await body(req);let c;do c=code();while(rooms.has(c));const pid=id(),token=id();const visibility=b.visibility==='public'?'public':'private';if(visibility==='private'&&!String(b.password||'').trim())return json(res,400,{error:'PASSWORD_REQUIRED'});const password=visibility==='private'?crypto.createHash('sha256').update(String(b.password)).digest('hex'):null;const r={code:c,status:'LOBBY',hostId:pid,currentIndex:0,seq:0,touched:now(),createdAt:now(),catchSeq:0,visibility,password,stageId:String(b.stageId||'stage1'),difficulty:String(b.difficulty||'NORMAL'),players:[{id:pid,token,name:(b.name||'HOST').slice(0,16),characterId:b.characterId||'minamo',ready:false,connected:true,alive:true,slot:'A'}]};rooms.set(c,r);return json(res,200,{token,playerId:pid,room:pub(r)});}
 if(u.pathname==='/api/room/join'&&req.method==='POST'){const b=await body(req),r=roomOf(b.code);if(!r||r.status!=='LOBBY')return json(res,404,{error:'ROOM_NOT_FOUND'});if(r.password&&crypto.createHash('sha256').update(String(b.password||'')).digest('hex')!==r.password)return json(res,403,{error:'PASSWORD_REQUIRED'});if(r.players.length>=4)return json(res,409,{error:'ROOM_FULL'});const pid=id(),token=id();r.players.push({id:pid,token,name:(b.name||'PLAYER').slice(0,16),characterId:b.characterId||'hinoka',ready:false,connected:true,alive:true,slot:'ABCD'[r.players.length]});r.touched=now();send(r,'PLAYER_JOINED');return json(res,200,{token,playerId:pid,room:pub(r)});}
 if(u.pathname==='/api/room/action'&&req.method==='POST'){const b=await body(req),r=roomOf(b.code),p=player(r,b.token);if(!r||!p)return json(res,403,{error:'BAD_SESSION'});r.touched=now();
   if(b.action==='READY'){p.ready=!!b.ready;send(r,'PLAYER_READY');return json(res,200,{ok:true});}
   if(b.action==='CHARACTER'){if(r.status!=='LOBBY')return json(res,409,{error:'IN_GAME'});p.characterId=b.characterId;send(r,'PLAYER_CHARACTER');return json(res,200,{ok:true});}
   if(b.action==='START'){if(p.id!==r.hostId)return json(res,403,{error:'HOST_ONLY'});if(r.players.length<2||!r.players.every(x=>x.ready))return json(res,409,{error:'NEED_2_TO_4_READY'});r.status='PLAYING';r.currentIndex=0;r.phase='WAIT_THROW';r.field=makeField();r.talk50Triggered=false;r.lastThrowPlayerId=null;send(r,'GAME_START',{turnPlayerId:r.players[0].id,field:r.field});return json(res,200,{ok:true});}
   if(b.action==='THROW'){if(r.status!=='PLAYING'||r.phase!=='WAIT_THROW'||r.players[r.currentIndex]?.id!==p.id)return json(res,409,{error:'NOT_YOUR_TURN'});const turnPlayerId=p.id;r.lastThrowPlayerId=turnPlayerId;r.currentIndex=nextPlayable(r,r.currentIndex);r.phase='WAIT_CATCH';r.catchSeq++;r.catchExpected=r.players.filter(x=>x.alive!==false&&x.connected!==false).map(x=>x.id);r.catchResults={};send(r,'THROW',{fromPlayerId:turnPlayerId,nextPlayerId:r.players[r.currentIndex].id,throwData:b.throwData,special:!!b.special,field:r.field,catchPos:r.field?.catchPos,fieldPattern:r.field?.pattern,fieldSeed:r.field?.seed,catchSeq:r.catchSeq,eventId:id(),serverTime:now()});return json(res,200,{ok:true});}
   if(b.action==='TALK50'){if(r.status!=='PLAYING'||r.talk50Triggered||r.lastThrowPlayerId!==p.id)return json(res,409,{error:'TALK50_NOT_ALLOWED'});r.talk50Triggered=true;send(r,'TALK50',{talkId:String(b.talkId||'interest50'),fromPlayerId:p.id,eventId:id(),serverTime:now()});return json(res,200,{ok:true});}
   if(b.action==='CATCH'){if(r.status!=='PLAYING'||r.phase!=='WAIT_CATCH'||!r.catchExpected?.includes(p.id))return json(res,409,{error:'NOT_CATCH_PLAYER'});if(r.catchResults?.[p.id])return json(res,200,{ok:true,grade:r.catchResults[p.id].grade});const d=Number(b.deltaMs);const order=['PERFECT','GREAT','GOOD','MISS'];const grade=order.includes(b.grade)?b.grade:'MISS';r.catchResults[p.id]={grade,deltaMs:Number.isFinite(d)?d:null};send(r,'CATCH_PLAYER',{playerId:p.id,grade,deltaMs:Number.isFinite(d)?d:null});const pending=r.catchExpected.filter(pid=>!r.catchResults[pid]);if(!pending.length){r.phase='WAIT_THROW';r.field=makeField();send(r,'CATCH_ROUND',{results:r.catchResults,nextPlayerId:r.players[r.currentIndex]?.id,nextField:r.field,eventId:id(),serverTime:now()});}return json(res,200,{ok:true,grade});}
   if(b.action==='PLAYER_DOWN'){p.alive=false;if(r.players[r.currentIndex]?.id===p.id){for(let i=1;i<=r.players.length;i++){const n=(r.currentIndex+i)%r.players.length;if(r.players[n].alive!==false){r.currentIndex=n;break;}}}r.phase='WAIT_THROW';send(r,'PLAYER_DOWN',{playerId:p.id,nextPlayerId:r.players[r.currentIndex]?.id});return json(res,200,{ok:true});}
   return json(res,400,{error:'BAD_ACTION'});
 }
 if(u.pathname==='/api/events'){const r=roomOf(u.searchParams.get('code')),p=player(r,u.searchParams.get('token'));if(!r||!p){res.writeHead(403);return res.end();}p.connected=true;res.writeHead(200,{'content-type':'text/event-stream','cache-control':'no-cache','connection':'keep-alive','x-accel-buffering':'no'});res.write(`event: message\ndata: ${JSON.stringify({type:'STATE_SYNC',seq:r.seq,room:pub(r)})}\n\n`);if(!clients.has(p.id))clients.set(p.id,new Set());clients.get(p.id).add(res);req.on('close',()=>{clients.get(p.id)?.delete(res);p.connected=false;r.touched=now();const anyConnected=r.players.some(x=>(clients.get(x.id)?.size||0)>0);if(!anyConnected){rooms.delete(r.code);for(const x of r.players)clients.delete(x.id);return;}if(r.status==='PLAYING'){p.alive=false;const wasCurrent=r.players[r.currentIndex]?.id===p.id;if(wasCurrent){for(let i=1;i<=r.players.length;i++){const n=(r.currentIndex+i)%r.players.length;if(r.players[n].alive!==false&&r.players[n].connected!==false){r.currentIndex=n;break;}}r.phase='WAIT_THROW';}send(r,'PLAYER_DOWN',{playerId:p.id,nextPlayerId:r.players[r.currentIndex]?.id,disconnected:true,wasCurrent});}else send(r,'PLAYER_CONNECTION',{playerId:p.id,connected:false});});return;}
 let fp=u.pathname==='/'?'/online.html':u.pathname;fp=path.normalize(fp).replace(/^\.\.(\/|\\)/,'');const full=path.join(ROOT,fp);if(!full.startsWith(ROOT)||!fs.existsSync(full)||fs.statSync(full).isDirectory()){res.writeHead(404);return res.end('not found');}const ext=path.extname(full);const ct={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css','.webp':'image/webp','.png':'image/png','.json':'application/json'}[ext]||'application/octet-stream';res.writeHead(200,{'content-type':ct,'cache-control':'no-store, no-cache, must-revalidate','pragma':'no-cache','expires':'0'});fs.createReadStream(full).pipe(res);
}catch(e){json(res,500,{error:String(e.message||e)})}});
server.listen(PORT,'0.0.0.0',()=>console.log(`HEART STRIKE Online http://0.0.0.0:${PORT}`));