import * as THREE from '../lib/three.js';
import { STAGES, CHARACTERS } from '../data/GameData.js';
import { GameState } from '../core/StateMachine.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export class OnlineSession{
 constructor(g){this.g=g;this.lastSeq=-1;this.pendingCatch=null;this.pendingThrow=null;this.catchPos=null;this.catchSeq=0;this.fieldPattern=null;this.fieldSeed=1;this.optimisticThrow=false;this.lastThrowFrom=null;this.talk50Requested=false;this.install()}
 install(){if(new URLSearchParams(location.search).get('online')!=='1')return;this.root=document.createElement('div');this.root.id='onlineLobby';document.body.appendChild(this.root);this.root.innerHTML=`<div class="ol-card"><b>HEART STRIKE ONLINE</b><div class="ol-sub">2〜4人 PRIVATE ROOM</div><input id="olName" maxlength="16" value="PLAYER"><select id="olChar">${CHARACTERS.map(c=>`<option value="${c.id}">${c.name}</option>`).join('')}</select><button id="olCreate">ルームを作る</button><div class="ol-join"><input id="olCode" inputmode="numeric" maxlength="6" placeholder="ROOM CODE"><button id="olJoin">参加</button></div><div id="olStatus"></div><div id="olPlayers"></div><button id="olReady" hidden>READY</button><button id="olStart" hidden>START</button></div>`;let st=document.createElement('style');st.textContent=`#onlineLobby{position:fixed;inset:0;z-index:2147483647;background:linear-gradient(#eefaff,#dff5ff);display:grid;place-items:center;padding:20px;pointer-events:auto;color:#18304a}.ol-card{width:min(340px,100%);background:#ffffffee;border:1px solid #bce9f5;border-radius:22px;padding:20px;box-shadow:0 12px 40px #6bbbd633;text-align:center}.ol-card>b{font-family:var(--display);font-size:21px}.ol-sub{font-size:11px;color:#648096;margin:4px 0 16px}.ol-card input,.ol-card select,.ol-card button{box-sizing:border-box;width:100%;min-height:46px;margin:5px 0;border-radius:12px;border:1px solid #b9dbe6;padding:8px 12px;font:inherit}.ol-card button{background:#ff6fa8;color:white;font-weight:800;border:0}.ol-join{display:grid;grid-template-columns:1fr 90px;gap:6px}.ol-player{display:grid;grid-template-columns:28px 1fr auto;align-items:center;text-align:left;padding:8px;border-bottom:1px solid #e5f1f5}.ol-player i{font-style:normal;font-weight:800}.ol-player small{color:#688}.ol-player .ok{color:#20a56b}#olStatus{font-size:12px;margin:8px 0;color:#456}#olStart{background:#22b9d6}`;document.head.appendChild(st);const wire=(sel,fn)=>{const el=this.root.querySelector(sel);if(!el)return;el.style.pointerEvents='auto';el.style.touchAction='manipulation';let lock=false;const fire=e=>{e?.preventDefault?.();e?.stopPropagation?.();e?.stopImmediatePropagation?.();if(lock)return;lock=true;Promise.resolve(fn()).finally(()=>setTimeout(()=>lock=false,350))};el.onclick=fire;};wire('#olCreate',()=>this.create());wire('#olJoin',()=>this.join());wire('#olReady',()=>this.action('READY',{ready:true}));wire('#olStart',()=>this.action('START'));this.status('オンライン接続準備OK')}
 val(x){return this.root.querySelector(x).value} async post(u,d){let r=await fetch(u,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(d)}),j=await r.json();if(!r.ok)throw Error(j.error||r.status);return j}
 async create(){this.status('ルーム作成中…');try{this.bind(await this.post('/api/room/create',{name:this.val('#olName'),characterId:this.val('#olChar')}))}catch(e){console.error('[Online] create failed',e);this.status('作成エラー: '+e.message)}} async join(){this.status('参加中…');try{this.bind(await this.post('/api/room/join',{code:this.val('#olCode'),name:this.val('#olName'),characterId:this.val('#olChar')}))}catch(e){console.error('[Online] join failed',e);this.status('参加エラー: '+e.message)}}
 bind(j){this.code=j.room.code;this.token=j.token;this.playerId=j.playerId;this.room=j.room;this.connect();this.render()}
 connect(){this.es?.close();this.es=new EventSource(`/api/events?code=${this.code}&token=${this.token}`);this.es.onmessage=e=>{let m=JSON.parse(e.data);if(m.seq!=null&&m.seq<this.lastSeq)return;this.lastSeq=m.seq??this.lastSeq;this.room=m.room||this.room;if(m.room?.field)this.setField(m.room.field);this.render();this.onEvent(m)};this.es.onerror=()=>this.status('再接続中…')}
 async action(action,extra={}){try{return await this.post('/api/room/action',{code:this.code,token:this.token,action,...extra})}catch(e){this.status(e.message)}} status(s){let e=this.root?.querySelector('#olStatus');if(e)e.textContent=s}
 render(){if(!this.room)return;this.status(`ROOM ${this.room.code} • ${this.room.players.length}/4`);this.root.querySelector('#olPlayers').innerHTML=this.room.players.map(p=>`<div class="ol-player"><i>${p.slot}</i><div>${esc(p.name)}<br><small>${esc(CHARACTERS.find(c=>c.id===p.characterId)?.name||p.characterId)}</small></div><span class="${p.ready?'ok':''}">${p.ready?'READY':'WAIT'}</span></div>`).join('');this.root.querySelector('#olReady').hidden=this.room.status!=='LOBBY';this.root.querySelector('#olStart').hidden=!(this.room.status==='LOBBY'&&this.room.hostId===this.playerId&&this.room.players.length>=2&&this.room.players.every(p=>p.ready))}
 onEvent(m){if(m.type==='GAME_START')this.startGame(m.field);if(m.type==='THROW'){this.lastThrowFrom=m.fromPlayerId;this.setField(m.field||{pattern:m.fieldPattern,seed:m.fieldSeed,catchPos:m.catchPos});this.catchSeq=Number(m.catchSeq)||this.catchSeq;if(m.fromPlayerId===this.playerId){this.optimisticThrow=false}else this.remoteThrow(m);}if(m.type==='CATCH'){if(m.nextField){this.setField(m.nextField);this.fieldVersion=(this.fieldVersion||0)+1;if(this.g.sm.currentName===GameState.PLAYER_ATTACK)this.g.space.spawnForThrow(this.fieldPattern,this.fieldSeed)}if(m.playerId!==this.playerId)this.remoteCatch(m);}if(m.type==='TALK50')this.startTalk50(m);if(m.type==='PLAYER_CONNECTION'&&m.connected===false)this.remoteDisconnect(m);if(m.type==='PLAYER_DOWN')this.remoteDown(m)}
 startGame(field){this.root.style.display='none';this.g.online=this;this.setField(field);let party=this.room.players.map(p=>this.g.progress.character(p.characterId));this.g.setDifficulty('NORMAL');this.g.startStage(STAGES[0],party)}
 setField(f){if(!f)return;this.fieldPattern=f.pattern||this.fieldPattern;this.fieldSeed=Number(f.seed)||this.fieldSeed;this.setCatchPosition(f.catchPos,this.catchSeq)}
 setCatchPosition(pos,seq){this.catchPos=pos&&Number.isFinite(pos.x)&&Number.isFinite(pos.y)?{x:pos.x,y:pos.y}:null;this.catchSeq=Number(seq)||0} consumeCatchPosition(){const p=this.catchPos;this.catchPos=null;return p} serialize(th){return {power:th.power,spin:th.spin,strong:!!th.strong,start:[th.start.x,th.start.y,th.start.z],velocity:[th.velocity.x,th.velocity.y,th.velocity.z],curveAccel:th.curveAccel?[th.curveAccel.x,th.curveAccel.y,th.curveAccel.z]:null,direction:th.direction?[th.direction.x,th.direction.y,th.direction.z]:null}}
 deserialize(d){return {...d,start:new THREE.Vector3(...d.start),velocity:new THREE.Vector3(...d.velocity),curveAccel:d.curveAccel?new THREE.Vector3(...d.curveAccel):null,direction:d.direction?new THREE.Vector3(...d.direction):null}}
 sendThrow(th,special=false){this.lastThrowFrom=this.playerId;this.optimisticThrow=true;this.action('THROW',{throwData:this.serialize(th),special:!!special}).then(r=>{if(!r?.ok)this.optimisticThrow=false});return true}
 applyRemoteThrow(m){this.pendingThrow=null;this.g.sm.change(GameState.BALL_TO_BOSS,{th:this.deserialize(m.throwData),flick:{speed:0,dx:0,dy:0},special:m.special?{...this.g.cfg.special}:null})}
 remoteThrow(m){if(this.g.sm.currentName===GameState.PLAYER_ATTACK)this.applyRemoteThrow(m);else this.pendingThrow=m}
 requestTalk50(talk){if(!talk||this.talk50Requested||this.lastThrowFrom!==this.playerId)return;this.talk50Requested=true;this.action('TALK50',{talkId:talk.id}).then(r=>{if(!r?.ok)this.talk50Requested=false})}
 startTalk50(m){const A=this.g.affection;if(!A||A.heart50Triggered||A.activeTalk||A.answerMode)return;const talk=(A.data.talks||[]).find(t=>t.id===m.talkId)||(A.data.talks||[]).find(t=>t.at===50);if(!talk)return;this.pendingCatch=null;this.g.sm.change(GameState.TALK_QUESTION,{talk})}
 remoteDisconnect(m){if(!this.room||this.room.status!=='PLAYING')return}
 remoteDown(m){
  if(!this.g?.turn?.players)return;
  const i=this.room.players.findIndex(p=>p.id===m.playerId);
  if(i>=0&&this.g.turn.players[i])this.g.turn.players[i].hp=0;
  this.g.ui?.setPlayers?.(this.g.turn.players,this.g.turn.index);
  if(!m.disconnected)return;
  const ni=this.room.players.findIndex(p=>p.id===m.nextPlayerId);
  if(ni>=0)this.g.turn.index=ni;
  this.pendingCatch=null;
  if(this.g.sm.currentName===GameState.PLAYER_DEFENSE||this.g.sm.currentName===GameState.PLAYER_CATCH||this.g.sm.currentName===GameState.BOSS_RETURN){
    this.g.catchTarget?.hide?.();this.g.ball?.hide?.();
    this.g.applyCharacter(this.g.turn.current);
    this.g.ui?.setPlayers?.(this.g.turn.players,this.g.turn.index);
    this.g.sm.change(GameState.PLAYER_ATTACK);
  }
 } sendCatch(deltaMs,grade){return this.action('CATCH',{deltaMs,grade})} sendDown(){return this.action('PLAYER_DOWN')} remoteCatch(m){let s=this.g.sm.current;if(this.g.sm.currentName===GameState.PLAYER_DEFENSE&&!s.result){s.decide(m.grade);return}this.pendingCatch=m} update(){
  if(this.pendingThrow&&this.g.sm.currentName===GameState.PLAYER_ATTACK){const m=this.pendingThrow;this.applyRemoteThrow(m);return}
  if(!this.pendingCatch)return;let s=this.g.sm.current;if(this.g.sm.currentName===GameState.PLAYER_DEFENSE&&!s.result){const m=this.pendingCatch;this.pendingCatch=null;s.decide(m.grade)}
 } isMyTurn(){return this.room?.players[this.room.currentIndex]?.id===this.playerId} isDown(){return this.room?.players.find(p=>p.id===this.playerId)?.alive===false}
}
